### ISSUE TITLE
batch for cluster picker

### ISSUE THREAD

**Issue by antoine4ucsd** [ArtPoon/preprints#1]
Hi
After reading your nice mmpp paper, I was willing to apply the cluster picker batch that you wrote for the simulations. I started tweaking your code but I am not an expert...

When running my own batch (attached), I starts & generates initial CP results but I got the following error:

> $ python batch-cluster-picker.py 
PIRC 2 0.9 0.005
Traceback (most recent call last):
  File "batch-cluster-picker.py", line 59, in <module>
    res = clusterpick(f, treefile, boot, boot, dist, max_size)
  File "batch-cluster-picker.py", line 19, in clusterpick
    with open(outfile, 'rU') as handle:
IOError: [Errno 2] No such file or directory: '../data/PIRC.2_TRUE.fas.fasttree_clusterPicks_list.txt'

What is expected in the list file? I guess I am missing smthg obvious here.
[batch-cluster-picker.py.txt](https://github.com/ArtPoon/preprints/files/1637250/batch-cluster-picker.py.txt)

Any chance you can help me with that issue? 
(in my data folder, I put only one fas/tree file for now)
thanks!

**Comment by ArtPoon** [comment]
Hi @antoine4ucsd – based on the error message, it looks like the expected output file isn't present at the directory `../data`.  My hunch is that the ClusterPicker binary is either not present or not functioning in the expected way.  Can you please confirm:
1. that the jarfile `ClusterPicker_1.2.3.jar` is present in the same directory as the `batch-cluster-picker.py` script
2. that manually running the command being sent via `subprocess` doesn't return an error code
3. if you remove the `stdout=devnull` argument in the `subprocess.check_call` statement, can you send me the resulting output stream?

Also, please note that this particular script is only a wrapper around ClusterPicker for batch processing, and that the MMPP method (which is a completely different clustering method) has since been implemented in a more user-friendly form at http://github.com/PoonLab/clmp

**Comment by antoine4ucsd** [comment]
thanks!

**Comment by ArtPoon** [comment]
Huh.  Only ClusterPicker version 1.2.4 generates the `*_clusterPicks_list.txt` file -- version 1.2.3 doesn't.  I don't know how the batch script ended up with 1.2.3 because the copy on my workstation is calling version 1.2.4.  Grab a copy of the 1.2.4 jarfile and change the `subprocess` call to that version, and it should work hopefully.

**Comment by antoine4ucsd** [comment]
Perfect! I will let you know if it works fine

thanks ++
a

**Comment by antoine4ucsd** [comment]
it works with version 1.2.5 of clusterpicker!
thanks again
